### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by brinkgit** [veista/smartthings#102]
In the log I find the next warning:

```
Logger: homeassistant.util.loop
Bron: util/loop.py:99
Eerst voorgekomen: 13:54:08 (48 gebeurtenissen)
Laatst gelogd: 14:11:00

Detected blocking call to import_module inside the event loop by custom integration 'smartthings' at custom_components/smartthings/__init__.py, line 291: platform_module = importlib.import_module( (offender: /config/custom_components/smartthings/__init__.py, line 291: platform_module = importlib.import_module(), please create a bug report at https://github.com/veista/smartthings/issues
```

It askes to report here, so I do

**Comment by cedricboitte** [comment]
Same situation here ...

Detected blocking call to import_module inside the event loop by custom integration 'smartthings' at custom_components/smartthings/__init__.py, line 291: platform_module = importlib.import_module( (offender: /config/custom_components/smartthings/__init__.py, line 291: platform_module = importlib.import_module(), please create a bug report at https://github.com/veista/smartthings/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 120, in post await hass.config_entries.async_reload(entry_id) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1897, in async_reload return await self.async_setup(entry_id, _lock=False) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1821, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/smartthings/__init__.py", line 157, in async_setup_entry broker = DeviceBroker(hass, entry, token, smart_app, devices, scenes) File "/config/custom_components/smartthings/__init__.py", line 280, in __init__ self._assignments = self._assign_capabilities(devices) File "/config/custom_components/smartthings/__init__.py", line 291, in _assign_capabilities platform_module = importlib.import_module(

**Comment by cgraf** [comment]
https://github.com/veista/smartthings/issues/96#issuecomment-2269116367
