### ISSUE TITLE
Can't connect at all, using Nabu Casa Cloud

### ISSUE THREAD

**Issue by Patrick1610** [veista/smartthings#104]
Hi! 
I have a personal access token and try to set this up, but I keep getting the following error during setup: 
![image](https://github.com/veista/smartthings/assets/6585375/34d3018b-a16e-43a4-848d-2db0147e6a32)
When I try to access the provided callback url I get this: 
![image](https://github.com/veista/smartthings/assets/6585375/1b4ade46-ce6c-45c0-a85f-b810dd3c934e)

Any idea what the problem could be? 
I have tried deleting the entire repository, restarting the host device and retrying the complete process. 
I have deleted my original smartthings installation so that can't be in the way. 

Regards Patrick

**Comment by Patrick1610** [comment]
Here are the debug-logs.

This error originated from a custom integration.

Logger: custom_components.smartthings.config_flow
Source: custom_components/smartthings/config_flow.py:124
integration: SmartThings
First occurred: 12:03:18 (2 occurrences)
Last logged: 12:03:20

API error setting up the SmartApp: {'requestId': '1232338831995509020', 'error': {'code': 'ConstraintViolationError', 'message': 'The request is malformed.', 'details': [{'code': 'TargetNon200Error', 'target': 'https://hooks.nabu.casa/gAAAAABmQct-00xDbszNr9dBzVY7EEitI7ZCgDtuHyToc-Otkg9sNJZ36w9L4X0QvBYZkNHPAIxnHO6IO4Jo2r82ULzDrjpqaFBdBmrHEvKYorufvreQRpEdjIjZ2bt-iN0t11nyWBi0XaeyAlMCgbpA5FVCxSX16oT4uyj0wLBbvCoR9jy99hg=', 'message': 'Target did not respond with a 200 status. Upstream status code=404', 'details': []}]}}
API error setting up the SmartApp: {'requestId': '5484562151554660269', 'error': {'code': 'ConstraintViolationError', 'message': 'The request is malformed.', 'details': [{'code': 'TargetNon200Error', 'target': 'https://hooks.nabu.casa/gAAAAABmQct-00xDbszNr9dBzVY7EEitI7ZCgDtuHyToc-Otkg9sNJZ36w9L4X0QvBYZkNHPAIxnHO6IO4Jo2r82ULzDrjpqaFBdBmrHEvKYorufvreQRpEdjIjZ2bt-iN0t11nyWBi0XaeyAlMCgbpA5FVCxSX16oT4uyj0wLBbvCoR9jy99hg=', 'message': 'Target did not respond with a 200 status. Upstream status code=404', 'details': []}]}}
Traceback (most recent call last):
  File "/config/custom_components/smartthings/config_flow.py", line 124, in async_step_pat
    app, client = await create_app(self.hass, self.api)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings/smartapp.py", line 144, in create_app
    app, client = await api.create_app(app)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/smartthings.py", line 110, in create_app
    entity = await self._service.create_app(app.to_data())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 171, in create_app
    return await self.post(API_APPS, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 368, in request
    raise APIResponseError(
pysmartthings.errors.APIResponseError: Unprocessable Entity (422): {"requestId": "1232338831995509020", "error": {"code": "ConstraintViolationError", "message": "The request is malformed.", "details": [{"code": "TargetNon200Error", "target": "https://hooks.nabu.casa/gAAAAABmQct-00xDbszNr9dBzVY7EEitI7ZCgDtuHyToc-Otkg9sNJZ36w9L4X0QvBYZkNHPAIxnHO6IO4Jo2r82ULzDrjpqaFBdBmrHEvKYorufvreQRpEdjIjZ2bt-iN0t11nyWBi0XaeyAlMCgbpA5FVCxSX16oT4uyj0wLBbvCoR9jy99hg=", "message": "Target did not respond with a 200 status. Upstream status code=404", "details": []}]}}

**Comment by Patrick1610** [comment]
When I look under Setting -> Home Assistant Cloud -> Webhooks, I see another URL then the Integration is trying to use. Unfortunately I cannot change the URL of the webhook in the settings.
