### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mshibla1** [veista/smartthings#11]
Hi - thank you so much for your work on this.  I am getting the following error while trying to start the integration (have tried beta version and release version).  Any help you could provide would be great!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/smartthings/__init__.py", line 148, in async_setup_entry
    await smartapp_sync_subscriptions(
  File "/config/custom_components/smartthings/smartapp.py", line 362, in smartapp_sync_subscriptions
    for disabled_capability in disabled_capabilities:
TypeError: 'NoneType' object is not iterable

**Comment by veista** [comment]
Please try the latest pre-release.

**Comment by mshibla1** [comment]
That did the trick.  Thank you so much!  I very much appreciate what you have created here.

**Comment by veista** [comment]
Great, You are most welcome. Please give the repo a star if you like it.
