### ISSUE TITLE
Samsung OCF Fridge Support

### ISSUE THREAD

**Issue by kernelpanic85** [veista/smartthings#27]
Hi,

Thanks for this fork of the Smartthings Integration! I have a TP6X_REF_16K model fridge and have tried adding the model to the 5 files (binary_sensor.py, number.py, sensor.py, select.py, and switch.py) as suggested in #20  and #22, however most of the entities are still not showing up for my fridge:

![image](https://user-images.githubusercontent.com/80057019/174108436-c39158b8-1017-488c-b436-310ff641086b.png)

![image](https://user-images.githubusercontent.com/80057019/174109372-e2a48266-6aa3-4b48-9aa7-2b3d30bcc950.png)

What am I missing?  Could someone point me in the right direction of how to troubleshoot?

**Comment by kernelpanic85** [comment]
```
Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 11:35:12 AM (96 occurrences)
Last logged: 12:08:26 PM

Exception in async_update_state when dispatching 'smartthings_update': ({'5C86C110-1031-0000-0000-000000000000'},) Traceback (most recent call last): File "/config/custom_components/smartthings/__init__.py", line 419, in async_update_state await self.async_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state if (is_on := self.is_on) is None: File "/config/custom_components/smartthings/binary_sensor.py", line 316, in is_on if self._device.status.attributes[Attribute.data].data["href"] == self._page: TypeError: 'NoneType' object is not subscriptable
```

**Comment by atkjedi** [comment]
thanks for this, it was the nudge I needed to update the integration with my new family hub
22K_REF_LCD_FHUB7.0, not 100% working but much closer

**Comment by DeathofaStar** [comment]
Experiencing the same issue as kernelpanic85 on my TP2X_REF_20K.  More details in issue below

[https://github.com/veista/smartthings/issues/51#issuecomment-1629348221](url)
