### ISSUE TITLE
Unsupported Home Assistant 2022.10. Please report it to the custom component author.

### ISSUE THREAD

**Issue by PerSterin** [veista/smartthings#31]
Thanks for the fork and better support for Samsung SmartThings.

Veista/Smartthings) release 1.1.13

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 21:09:39 (2 occurrences)
Last logged: 21:09:39

    custom_components.smartthings.number::SmartThingsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
    custom_components.smartthings.number::SamsungOcfTemperatureNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by djalexnl** [comment]
Same issue here i noticed in the logging!

**Comment by thenightflier74** [comment]
moreover, I noted that temperature sensor is not present while humidity sensor seems to work. In general, you can't set target temperature outside the graph GUI: no automation possible

**Comment by PerSterin** [comment]
**This is now becominga problem, as of Home Assistant 2022.10** 

**Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 18:18:08 (158 occurrences)
Last logged: 18:18:15**

Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 1153, in execute
    return await self.command(
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 825, in command
    response = await self._api.post_device_command(
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 147, in post_device_command
    return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 368, in request
    raise APIResponseError(
pysmartthings.errors.APIResponseError: Too Many Requests (429): {"requestId": "FD227ACD-D54B-4CCF-9CB4-1D3081DEC39E", "error": {"code": "TooManyRequestError", "message": "Too Many Requests", "details": [{"code": "TooManyRequestError", "message": "attempt 120 limit 120 - retry in 52286 millis", "details": []}]}}

**Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 18:18:08 (158 occurrences)
Last logged: 18:18:15
Error doing job: _GatheringFuture exception was never retrieved**

Traceback (most recent call last):

2022-10-07 18:18:15.664 ERROR (MainThread) [homeassistant] Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 1153, in execute
return await self.command(
File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 825, in command
response = await self._api.post_device_command(
File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 147, in post_device_command
return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 395, in post
return await self.request("post", self._api_base + resource, data=data)
File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 368, in request
raise APIResponseError(
pysmartthings.errors.APIResponseError: Too Many Requests (429): {"requestId": "EE2A937F-D9FE-47CE-B92A-31FFC6E7BA85", "error": {"code": "TooManyRequestError", "message": "Too Many Requests", "details": [{"code": "TooManyRequestError", "message": "attempt 277 limit 120 - retry in 44559 millis", "details": []}]}}
2022-10-07 18:37:57.417 ERROR (Recorder) [homeassistant] Error doing job: Task was destroyed but it is pending!

**Comment by PerSterin** [comment]
**Looks to solve our problem with, Smartthings: Unsupported in Home Assistant 2022.10**

https://github.com/beschoenen/smartthings/tree/f52d9448fd0bcf80b0611c016e59d49d17cf89e1

**Comment by PerSterin** [comment]
Thanks Again!
