### ISSUE TITLE
Exception in async_update_state when dispatching 'smartthings_update'

### ISSUE THREAD

**Issue by archerne** [veista/smartthings#46]
I have started getting this error, many many times a day. Any ideas on what is causing it?
```
Logger: homeassistant.util.logging
Source: util/logging.py:156
First occurred: November 30, 2022 at 10:16:41 PM (104 occurrences)
Last logged: 12:00:19 PM

Exception in async_update_state when dispatching 'smartthings_update': ({'c2383f76-31b5-f9ab-0d05-c80bf664372a'},) Traceback (most recent call last): File "/config/custom_components/smartthings/__init__.py", line 419, in async_update_state await self.async_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_update_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 982, in state if (is_on := self.is_on) is None: File "/config/custom_components/smartthings/switch.py", line 426, in is_on output = self._device.status.attributes[Attribute.data].value["payload"][ KeyError: 'x.com.samsung.da.iceMaker'
```

Device info
ARTIK051_REF_17K
by Samsung Electronics
Firmware: DA-REF-ART-COMMON-1_20201124

**Comment by veista** [comment]
Have you modified the integration files?

**Comment by archerne** [comment]
I have not modified anything.

**Comment by veista** [comment]
Ok. This is an issue with the fridge not having an icemaker I guess.

**Comment by archerne** [comment]
The fridge does have an icemaker though.

**Comment by archerne** [comment]
![Screenshot_20221202-095007](https://user-images.githubusercontent.com/561565/205332200-2d6f01ce-3c42-48f5-aacd-5ddf529bad91.png)
![Screenshot_20221202-094945](https://user-images.githubusercontent.com/561565/205332219-a3353b4f-579e-445c-8ae9-53763183261d.png)

**Comment by archerne** [comment]
I am also getting this error:
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 10:03:52 AM (21 occurrences)
Last logged: 10:03:52 AM

Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 1153, in execute
    return await self.command(
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 825, in command
    response = await self._api.post_device_command(
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 147, in post_device_command
    return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 368, in request
    raise APIResponseError(
pysmartthings.errors.APIResponseError: Too Many Requests (429): {"requestId": "A665182D-DD21-46D7-8699-10AEED77EF57", "error": {"code": "TooManyRequestError", "message": "Too Many Requests", "details": [{"code": "TooManyRequestError", "message": "attempt 121 limit 120 - retry in 7667 millis", "details": []}]}}

```
