### ISSUE TITLE
SmartThings "Failed to set up" after upgrade to Home Assistant 2023.6.1

### ISSUE THREAD

**Issue by Crepetsky** [veista/smartthings#76]
The integration was working great prior. Now, it states "Failed to set up" on the integrations page.

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smartthings/__init__.py:121
Integration: SmartThings
First occurred: 7:59:51 AM (2 occurrences)
Last logged: 8:00:58 AM

Error setting up entry Home for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings/__init__.py", line 121, in async_setup_entry
    token = await api.generate_tokens(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pysmartthings/smartthings.py", line 209, in generate_tokens
    result = await self._service.generate_tokens(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pysmartthings/api.py", line 424, in generate_tokens
    raise APIInvalidGrant(data.get("error_description"))
pysmartthings.errors.APIInvalidGrant: Invalid refresh token: 6a2a79d1-89be-4aaa-8cd4-182b7e3c88eb requested by clientId: 60bd00ab-a2bc-44f2-b956-200f390786cb with grantType: refresh_token, e.cause: no cause
`

**Comment by cfurini** [comment]
I am having the same issue

**Comment by cfurini** [comment]
I just deleted and reinstalled the integration and it is back working.
