### ISSUE TITLE
ImportError NumberMode

### ISSUE THREAD

**Issue by dimmuboy** [veista/smartthings#8]
After latest update integration stopped working.

```
Logger: homeassistant.config_entries
Source: custom_components/smartthings/number.py:12
Integration: SmartThings
First occurred: 14:54:57 (1 occurrences)
Last logged: 14:54:57

Error setting up entry My home for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/smartthings/__init__.py", line 157, in async_setup_entry
    broker = DeviceBroker(hass, entry, token, smart_app, devices, scenes)
  File "/config/custom_components/smartthings/__init__.py", line 278, in __init__
    self._assignments = self._assign_capabilities(devices)
  File "/config/custom_components/smartthings/__init__.py", line 289, in _assign_capabilities
    platform_module = importlib.import_module(
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/smartthings/number.py", line 12, in <module>
    from homeassistant.components.number import NumberEntity, NumberMode
ImportError: cannot import name 'NumberMode' from 'homeassistant.components.number' (/usr/src/homeassistant/homeassistant/components/number/__init__.py)
```

**Comment by veista** [comment]
Which version do you have of the integration and which version of Home Assistant?

**Comment by dimmuboy** [comment]
Okay, it works after HASS upgrade. Sorry for false issue :)
